Django Home Page new test cases
ChicoState/open-source-security-camera pull request #84
Opened 2022-05-04 20:13 UTC by kevdouglass

Added Django Test Case for

 - (User and Http Responses Valid response)
- Made 'Media' Directory visible for serving dynamic img's and video's with a relative path.
- script for camerPortScan.py that will be used to scan ports to check that user has a visible camera for OpenCV script.

2022-05-09 07:10 UTC, melippmann requested changes
generally looks good, please clean up linting and let remove commented out code, notify me when this is done and I will accept the PR.

2022-05-09 07:10 UTC, melippmann commented on osCam/osCam/urls.py
> +# urlpatterns += urlpatterns('',
remove old commented out code from PRs

2022-05-09 07:10 UTC, melippmann commented on osCam/templates/core/home.html
> +                        <!-- <img src="../../video/vault.jpg"> -->
remove comment

2022-05-13 16:50 UTC, DJ-IRL commented
pending meher's OK this all looks good to me

2022-05-15 01:12 UTC, melippmann commented on osCam/core/tests.py
> +        'PORTNUM': 0,
please remove port num

2022-05-15 20:57 UTC, melippmann approved these changes

2022-05-15 20:58 UTC, merged